const admin=require('firebase-admin');
const crypto=require('crypto');
function clean(v,max=120){return String(v==null?'':v).trim().slice(0,max)}
function normCode(v){return clean(v,40).toUpperCase().replace(/[^A-Z0-9_-]+/g,'')}
function amount(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n)):0}
function tsMs(v){try{return v?.toMillis?v.toMillis():Number(v?.seconds||v?._seconds||0)*1000||Number(v)||0}catch(_){return 0}}
function usageId(code,uid){return `${normCode(code)}_${crypto.createHash('sha256').update(String(uid||'')).digest('hex').slice(0,24)}`}
function computeDiscount(data={},subtotalUZS=0){const subtotal=amount(subtotalUZS),type=clean(data.type||data.discountType||'percent',20).toLowerCase(),value=Math.max(0,Number(data.value??data.discountValue??0)||0),max=amount(data.maxDiscountUZS||0);let out=type==='fixed'?amount(value):amount(subtotal*value/100);if(max>0)out=Math.min(out,max);return Math.min(subtotal,out)}
function validate(data={},usage={},subtotalUZS=0){const now=Date.now(),min=amount(data.minOrderUZS||0),subtotal=amount(subtotalUZS),limit=amount(data.usageLimit||0),used=amount(data.usedCount||0),per=Math.max(0,Math.round(Number(data.perUserLimit??1)||0)),usedBy=amount(usage.usedCount||0);if(data.active===false)throw new Error('PROMO_INACTIVE');if(tsMs(data.startAt)&&now<tsMs(data.startAt))throw new Error('PROMO_NOT_STARTED');if(tsMs(data.expiresAt)&&now>tsMs(data.expiresAt))throw new Error('PROMO_EXPIRED');if(subtotal<min)throw new Error('PROMO_MIN_ORDER');if(limit>0&&used>=limit)throw new Error('PROMO_LIMIT_REACHED');if(per>0&&usedBy>=per)throw new Error('PROMO_USER_LIMIT');const discountUZS=computeDiscount(data,subtotal);if(discountUZS<=0)throw new Error('PROMO_INVALID');return{discountUZS,minOrderUZS:min,type:clean(data.type||data.discountType||'percent',20).toLowerCase(),value:Number(data.value??data.discountValue??0)||0,maxDiscountUZS:amount(data.maxDiscountUZS||0)}}
async function previewPromo(db,{code,uid,subtotalUZS=0}={}){const c=normCode(code);if(!c)throw new Error('PROMO_CODE_REQUIRED');const promo=await db.doc(`promocodes/${c}`).get();if(!promo.exists)throw new Error('PROMO_NOT_FOUND');const usage=await db.doc(`promoUsages/${usageId(c,uid)}`).get();const quote=validate(promo.data()||{},usage.exists?(usage.data()||{}):{},subtotalUZS);return{code:c,...quote}}
async function preparePromo(tx,db,{code,uid,subtotalUZS=0,orderId=''}={}){const c=normCode(code);if(!c)return{code:'',discountUZS:0,apply:()=>{}};const promoRef=db.doc(`promocodes/${c}`),usageRef=db.doc(`promoUsages/${usageId(c,uid)}`);const [promoSnap,usageSnap]=await Promise.all([tx.get(promoRef),tx.get(usageRef)]);if(!promoSnap.exists)throw new Error('PROMO_NOT_FOUND');const quote=validate(promoSnap.data()||{},usageSnap.exists?(usageSnap.data()||{}):{},subtotalUZS);return{code:c,...quote,apply:()=>{tx.set(promoRef,{usedCount:admin.firestore.FieldValue.increment(1),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});tx.set(usageRef,{code:c,uid:String(uid||''),usedCount:admin.firestore.FieldValue.increment(1),lastOrderId:String(orderId||''),updatedAt:admin.firestore.FieldValue.serverTimestamp(),createdAt:usageSnap.exists?(usageSnap.data()?.createdAt||admin.firestore.FieldValue.serverTimestamp()):admin.firestore.FieldValue.serverTimestamp()},{merge:true})}}}
module.exports={normCode,amount,computeDiscount,previewPromo,preparePromo};
