const C=require('./_sellerCommon');
const arr=v=>Array.isArray(v)?v:[];
const txt=(v,n=500)=>C.safeText(v,n);
const money=v=>Math.max(0,Math.round(Number(v)||0));
const ts=v=>{try{return v?.toMillis?v.toMillis():Number(v?.seconds||v?._seconds||0)*1000||Number(v)||0}catch(_){return 0}};
function cleanImages(v){return arr(v).map(x=>txt(x,900)).filter(Boolean).slice(0,18)}
function cleanTextArray(v,max=80,limit=50){return arr(v).map(x=>txt(x,max)).filter(Boolean).slice(0,limit)}
function cleanColors(v){return arr(v).map(x=>typeof x==='string'?x:{name:txt(x?.name,80),hex:txt(x?.hex,30),image:txt(x?.image||x?.img||x?.imageUrl,900)}).filter(x=>typeof x==='string'?!!x:!!x.name).slice(0,48)}
function cleanVariants(v){return arr(v).map(x=>({color:txt(x?.color,80)||null,size:txt(x?.size,80)||null,price:money(x?.price??x?.priceUZS),oldPrice:money(x?.oldPrice),sku:txt(x?.sku||x?.skuId,100),stockQty:Math.max(0,Math.round(Number(x?.stockQty??x?.stock)||0)),image:txt(x?.image,900),attributes:x?.attributes&&typeof x.attributes==='object'?Object.fromEntries(Object.entries(x.attributes).slice(0,12).map(([k,val])=>[txt(k,100),txt(val,120)]).filter(([k,val])=>k&&val)):{} })).slice(0,220)}
function cleanImagesByColor(v){const out={};if(v&&typeof v==='object')Object.entries(v).slice(0,30).forEach(([k,urls])=>{const key=txt(k,80),imgs=cleanImages(urls);if(key&&imgs.length)out[key]=imgs});return out}
function cleanLocalizedSelections(v){const out={};if(v&&typeof v==='object'&&!Array.isArray(v))Object.entries(v).slice(0,14).forEach(([k,val])=>{const key=txt(k,140),value=txt(val,180);if(key&&value)out[key]=value});return out}
function cleanExternalCatalog(d={}){const raw=d.externalCatalog||d.china1688Catalog||d.externalMarket?.customerCatalog||d.china1688?.customerCatalog;if(!raw||typeof raw!=='object')return null;const optionGroups=arr(raw.optionGroups).slice(0,10).map((g,gi)=>({id:txt(g?.id||`g${gi+1}`,140),name:txt(g?.name||'Variant',180),name_ru:txt(g?.name_ru||g?.nameRu,180),name_en:txt(g?.name_en||g?.nameEn,180),type:txt(g?.type||'other',20),required:g?.required!==false,options:arr(g?.options).slice(0,96).map((o,oi)=>({id:txt(o?.id||`o${oi+1}`,140),name:txt(o?.name,180),name_ru:txt(o?.name_ru||o?.nameRu,180),name_en:txt(o?.name_en||o?.nameEn,180),image:txt(o?.image,900),disabled:o?.disabled===true})).filter(o=>o.name)})).filter(g=>g.id&&g.options.length);const skus=arr(raw.skus).slice(0,240).map((row,ri)=>({id:txt(row?.id||`sku${ri+1}`,160),skuId:txt(row?.skuId||row?.id||`sku${ri+1}`,160),name:txt(row?.name,320),name_ru:txt(row?.name_ru||row?.nameRu,320),name_en:txt(row?.name_en||row?.nameEn,320),selections:cleanLocalizedSelections(row?.selections||row?.externalOptions||row?.chinaOptions),selections_ru:cleanLocalizedSelections(row?.selections_ru||row?.selectionsRu),selections_en:cleanLocalizedSelections(row?.selections_en||row?.selectionsEn),price:money(row?.price??row?.priceUZS),image:txt(row?.image,900),disabled:row?.disabled===true,stockKnown:false}));return{version:Number(raw.version||1)||1,kind:'external-market-catalog',optionGroups,skus,optionGroupCount:optionGroups.length,skuCount:skus.length,hasVariants:optionGroups.length>0}}
function derivedColors(d={}){const base=cleanColors(d.colors);if(base.length)return base;const map=new Map();arr(d.variants).forEach(v=>{const name=txt(v?.color,80);if(!name)return;const old=map.get(name)||{};map.set(name,{name,image:txt(v?.image,900)||old.image||''})});return [...map.values()].slice(0,48)}
function derivedSizes(d={}){const base=cleanTextArray(d.sizes,80,40);if(base.length)return base;return [...new Set(arr(d.variants).map(v=>txt(v?.size,80)).filter(Boolean))].slice(0,80)}
function visibleProduct(d={}){return String(d.status||'').toLowerCase()==='approved'&&d.isActive!==false&&d.sellerActive!==false}
function stockQty(d={}){const variants=arr(d.variants);if(variants.length){return variants.reduce((sum,v)=>sum+Math.max(0,Math.round(Number(v?.stockQty)||0)),0)}return Math.max(0,Math.round(Number(d.stockQty??d.stock)||0))}
function minPrice(d={}){const prices=arr(d.variants).map(v=>money(v?.price??v?.priceUZS)).filter(Boolean);const base=money(d.price??d.priceUZS);return prices.length?Math.min(...prices,base||Infinity):base}
function publicProduct(id,d={}){return{
  id:String(d.id||id),name:txt(d.name||d.title,240),name_ru:txt(d.name_ru,240),name_en:txt(d.name_en,240),description:txt(d.description||d.desc,6000),description_ru:txt(d.description_ru,6000),description_en:txt(d.description_en,6000),subtitle:txt(d.subtitle,240),price:money(d.price??d.priceUZS),oldPrice:money(d.oldPrice),currency:txt(d.currency||'UZS',20),images:cleanImages(d.images),imagesByColor:cleanImagesByColor(d.imagesByColor),image:txt(d.image||d.imageUrl,900),colors:derivedColors(d),sizes:derivedSizes(d),variants:cleanVariants(d.variants),tags:cleanTextArray(d.tags,100,50),badges:cleanTextArray(d.badges,100,10),badge:txt(d.badge,100),categoryId:txt(d.categoryId,100),subcategoryId:txt(d.subcategoryId,100),categoryPathIds:cleanTextArray(d.categoryPathIds,100,8),sku:txt(d.sku||d.article,120),stockQty:stockQty(d),weightKg:Number(d.weightKg??d.weight??0)||0,productType:txt(d.productType||d.authType,40),youtubeUrl:txt(d.youtubeUrl||d.videoUrl,1400),videoUrl:txt(d.videoUrl||d.youtubeUrl,1400),videoPoster:txt(d.videoPoster||d.externalMarket?.videoPoster,900),fulfillmentType:txt(d.fulfillmentType||d.fulfillment||'stock',50),originCountry:txt(d.originCountry||d.externalMarket?.originCountry,4),customerOrigin:txt(d.customerOrigin||d.externalMarket?.customerOrigin,40),externalCatalog:cleanExternalCatalog(d),deliveryMinDays:Number(d.deliveryMinDays||1)||1,deliveryMaxDays:Number(d.deliveryMaxDays||7)||7,prepayRequired:!!d.prepayRequired,popularScore:C.productPopularity(d),metricScore:C.metricMax(d.metricScore,d.engagementScore,d.score),engagementScore:C.metricMax(d.engagementScore,d.metricScore,d.score),views:C.metricMax(d.views,d.viewCount,d.viewsCount,d.productViews,d.popularViews),viewsCount:C.metricMax(d.views,d.viewCount,d.viewsCount,d.productViews,d.popularViews),cartAdds:C.metricMax(d.cartAdds,d.cartAddCount,d.addToCartCount),favoriteAdds:C.metricMax(d.favoriteAdds,d.favorites,d.favoriteCount,d.wishlistAdds),purchases:C.metricMax(d.purchases,d.purchaseCount,d.soldCount,d.salesCount),soldCount:C.metricMax(d.soldCount,d.purchases,d.purchaseCount,d.salesCount),sellerId:txt(d.sellerId,100),sellerName:txt(d.sellerName,180),sellerLogo:txt(d.sellerLogo,900),sellerPopularity:C.storePopularityNum(d.sellerPopularity),sellerVerified:d.sellerVerified!==false,sellerActive:d.sellerActive!==false,isOrzuMallVerified:d.isOrzuMallVerified===true||String(d.ownerType||'').toLowerCase()==='orzumall'||String(d.createdByRole||'').toLowerCase()==='admin'||(!d.sellerId&&!d.ownerUid&&!d.ownerEmail),ownerType:txt(d.ownerType||(!d.sellerId?'orzumall':'seller'),40),createdByRole:txt(d.createdByRole||(!d.sellerId?'admin':'seller'),40),status:'approved',_created:ts(d.createdAt||d.updatedAt),_price:minPrice(d)
}}
function norm(v){return txt(v,2400).toLowerCase().replace(/[’`ʻʼ]/g,"'").replace(/\s+/g,' ').trim()}
function searchHay(p={}){return norm([p.name,p.name_ru,p.name_en,p.sku,p.article,p.categoryId,p.subcategoryId,...arr(p.categoryPathIds),...arr(p.tags),p.sellerName,p.description,p.description_ru,p.description_en].join(' '))}
function searchRank(p={},raw=''){const q=norm(raw);if(!q)return 0;const name=norm(p.name),ru=norm(p.name_ru),en=norm(p.name_en),sku=norm(p.sku||p.article),hay=searchHay(p);let score=0;if(name===q||ru===q||en===q)score+=1400;if(sku===q)score+=1350;if(name.startsWith(q)||ru.startsWith(q)||en.startsWith(q))score+=700;if(name.includes(q)||ru.includes(q)||en.includes(q))score+=430;if(sku.includes(q))score+=380;if(hay.includes(q))score+=120;for(const token of q.split(' ').filter(Boolean)){if(hay.includes(token))score+=45}return score?score+Math.min(300,C.productPopularity(p))/8:0}
function recommendationRank(p={},ctx={}){const ids=new Set(arr(ctx.excludeIds).map(String));if(ids.has(String(p.id)))return -1;let score=Math.min(500,C.productPopularity(p))/5;const cats=new Set(arr(ctx.categoryIds).map(norm));const tags=new Set(arr(ctx.tags).map(norm));const sellers=new Set(arr(ctx.sellerIds).map(String));if(arr(p.categoryPathIds).some(x=>cats.has(norm(x)))||cats.has(norm(p.categoryId))||cats.has(norm(p.subcategoryId)))score+=150;if(arr(p.tags).some(x=>tags.has(norm(x))))score+=90;if(p.sellerId&&sellers.has(String(p.sellerId)))score+=40;if(stockQty(p)<=0)score-=100;return score}
async function loadApproved(db,limitCount=1200){let snap;try{snap=await db.collection('products').where('status','==','approved').limit(Math.max(1,Math.min(2200,Number(limitCount)||1200))).get()}catch(_){snap=await db.collection('products').limit(Math.max(1,Math.min(2200,Number(limitCount)||1200))).get()}const rows=await C.withProductMetrics(db,snap.docs);return rows.filter(visibleProduct)}
module.exports={arr,txt,money,ts,visibleProduct,stockQty,minPrice,publicProduct,norm,searchRank,recommendationRank,loadApproved};
