const C=require('./_sellerCommon');
const arr=v=>Array.isArray(v)?v:[];
const txt=(v,n=500)=>C.safeText(v,n);
const money=v=>Math.max(0,Math.round(Number(v)||0));
const ts=v=>{try{return v?.toMillis?v.toMillis():Number(v?.seconds||v?._seconds||0)*1000||Number(v)||0}catch(_){return 0}};
function cleanImages(v){return arr(v).map(x=>txt(x,900)).filter(Boolean).slice(0,18)}
function cleanTextArray(v,max=80,limit=50){return arr(v).map(x=>txt(x,max)).filter(Boolean).slice(0,limit)}
function cleanColors(v){return arr(v).map(x=>typeof x==='string'?x:{name:txt(x?.name,80),hex:txt(x?.hex,30)}).slice(0,30)}
function cleanVariants(v){return arr(v).map(x=>({color:txt(x?.color,80)||null,size:txt(x?.size,80)||null,price:money(x?.price??x?.priceUZS),oldPrice:money(x?.oldPrice),sku:txt(x?.sku,100),stockQty:Math.max(0,Math.round(Number(x?.stockQty)||0))})).slice(0,120)}
function cleanImagesByColor(v){const out={};if(v&&typeof v==='object')Object.entries(v).slice(0,30).forEach(([k,urls])=>{const key=txt(k,80),imgs=cleanImages(urls);if(key&&imgs.length)out[key]=imgs});return out}
function visibleProduct(d={}){return String(d.status||'').toLowerCase()==='approved'&&d.isActive!==false&&d.sellerActive!==false}
function stockQty(d={}){const variants=arr(d.variants);if(variants.length){return variants.reduce((sum,v)=>sum+Math.max(0,Math.round(Number(v?.stockQty)||0)),0)}return Math.max(0,Math.round(Number(d.stockQty??d.stock)||0))}
function minPrice(d={}){const prices=arr(d.variants).map(v=>money(v?.price??v?.priceUZS)).filter(Boolean);const base=money(d.price??d.priceUZS);return prices.length?Math.min(...prices,base||Infinity):base}
function publicProduct(id,d={}){return{
  id:String(d.id||id),name:txt(d.name||d.title,240),name_ru:txt(d.name_ru,240),description:txt(d.description||d.desc,6000),description_ru:txt(d.description_ru,6000),subtitle:txt(d.subtitle,240),price:money(d.price??d.priceUZS),oldPrice:money(d.oldPrice),currency:txt(d.currency||'UZS',20),images:cleanImages(d.images),imagesByColor:cleanImagesByColor(d.imagesByColor),image:txt(d.image||d.imageUrl,900),colors:cleanColors(d.colors),sizes:cleanTextArray(d.sizes,80,40),variants:cleanVariants(d.variants),tags:cleanTextArray(d.tags,100,50),badges:cleanTextArray(d.badges,100,10),badge:txt(d.badge,100),categoryId:txt(d.categoryId,100),subcategoryId:txt(d.subcategoryId,100),categoryPathIds:cleanTextArray(d.categoryPathIds,100,8),sku:txt(d.sku||d.article,120),stockQty:stockQty(d),weightKg:Number(d.weightKg??d.weight??0)||0,productType:txt(d.productType||d.authType,40),youtubeUrl:txt(d.youtubeUrl||d.videoUrl,900),fulfillmentType:txt(d.fulfillmentType||d.fulfillment||'stock',50),deliveryMinDays:Number(d.deliveryMinDays||1)||1,deliveryMaxDays:Number(d.deliveryMaxDays||7)||7,prepayRequired:!!d.prepayRequired,popularScore:C.productPopularity(d),metricScore:C.metricMax(d.metricScore,d.engagementScore,d.score),engagementScore:C.metricMax(d.engagementScore,d.metricScore,d.score),views:C.metricMax(d.views,d.viewCount,d.viewsCount,d.productViews,d.popularViews),viewsCount:C.metricMax(d.views,d.viewCount,d.viewsCount,d.productViews,d.popularViews),cartAdds:C.metricMax(d.cartAdds,d.cartAddCount,d.addToCartCount),favoriteAdds:C.metricMax(d.favoriteAdds,d.favorites,d.favoriteCount,d.wishlistAdds),purchases:C.metricMax(d.purchases,d.purchaseCount,d.soldCount,d.salesCount),soldCount:C.metricMax(d.soldCount,d.purchases,d.purchaseCount,d.salesCount),sellerId:txt(d.sellerId,100),sellerName:txt(d.sellerName,180),sellerLogo:txt(d.sellerLogo,900),sellerPopularity:C.storePopularityNum(d.sellerPopularity),sellerVerified:d.sellerVerified!==false,sellerActive:d.sellerActive!==false,isOrzuMallVerified:d.isOrzuMallVerified===true||String(d.ownerType||'').toLowerCase()==='orzumall'||String(d.createdByRole||'').toLowerCase()==='admin'||(!d.sellerId&&!d.ownerUid&&!d.ownerEmail),ownerType:txt(d.ownerType||(!d.sellerId?'orzumall':'seller'),40),createdByRole:txt(d.createdByRole||(!d.sellerId?'admin':'seller'),40),status:'approved',_created:ts(d.createdAt||d.updatedAt),_price:minPrice(d)
}}
function norm(v){return txt(v,2400).toLowerCase().replace(/[’`ʻʼ]/g,"'").replace(/\s+/g,' ').trim()}
function searchHay(p={}){return norm([p.name,p.name_ru,p.sku,p.article,p.categoryId,p.subcategoryId,...arr(p.categoryPathIds),...arr(p.tags),p.sellerName,p.description,p.description_ru].join(' '))}
function searchRank(p={},raw=''){const q=norm(raw);if(!q)return 0;const name=norm(p.name),ru=norm(p.name_ru),sku=norm(p.sku||p.article),hay=searchHay(p);let score=0;if(name===q||ru===q)score+=1400;if(sku===q)score+=1350;if(name.startsWith(q)||ru.startsWith(q))score+=700;if(name.includes(q)||ru.includes(q))score+=430;if(sku.includes(q))score+=380;if(hay.includes(q))score+=120;for(const token of q.split(' ').filter(Boolean)){if(hay.includes(token))score+=45}return score?score+Math.min(300,C.productPopularity(p))/8:0}
function recommendationRank(p={},ctx={}){const ids=new Set(arr(ctx.excludeIds).map(String));if(ids.has(String(p.id)))return -1;let score=Math.min(500,C.productPopularity(p))/5;const cats=new Set(arr(ctx.categoryIds).map(norm));const tags=new Set(arr(ctx.tags).map(norm));const sellers=new Set(arr(ctx.sellerIds).map(String));if(arr(p.categoryPathIds).some(x=>cats.has(norm(x)))||cats.has(norm(p.categoryId))||cats.has(norm(p.subcategoryId)))score+=150;if(arr(p.tags).some(x=>tags.has(norm(x))))score+=90;if(p.sellerId&&sellers.has(String(p.sellerId)))score+=40;if(stockQty(p)<=0)score-=100;return score}
async function loadApproved(db,limitCount=1200){let snap;try{snap=await db.collection('products').where('status','==','approved').limit(Math.max(1,Math.min(2200,Number(limitCount)||1200))).get()}catch(_){snap=await db.collection('products').limit(Math.max(1,Math.min(2200,Number(limitCount)||1200))).get()}const rows=await C.withProductMetrics(db,snap.docs);return rows.filter(visibleProduct)}
module.exports={arr,txt,money,ts,visibleProduct,stockQty,minPrice,publicProduct,norm,searchRank,recommendationRank,loadApproved};
