/* OrzuMall v175 — secure admin user center.
 * Plain-text passwords are never readable. Admin may set a new temporary
 * password. Sensitive actions are written to admin_user_audit.
 */
const admin=require('firebase-admin');
const crypto=require('node:crypto');

function initAdmin(){if(admin.apps.length)return;const raw=String(process.env.FIREBASE_SERVICE_ACCOUNT_B64||'').replace(/\s+/g,'');if(!raw)throw new Error('FIREBASE_SERVICE_ACCOUNT_B64_MISSING');const serviceAccount=JSON.parse(Buffer.from(raw,'base64').toString('utf8'));admin.initializeApp({credential:admin.credential.cert(serviceAccount)})}
function json(statusCode,body){return{statusCode,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization','access-control-allow-methods':'POST, OPTIONS'},body:JSON.stringify(body)}}
function bearer(e){const h=e.headers||{},m=String(h.authorization||h.Authorization||'').match(/^Bearer\s+(.+)$/i);return m?m[1]:''}
function txt(v,max=240){return String(v==null?'':v).replace(/\s+/g,' ').trim().slice(0,max)}
function email(v){return txt(v,180).toLowerCase()}
function num(v,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function phone(v){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('998'))d=d.slice(3);d=d.slice(0,9);return d.length===9?`+998${d}`:''}
function pseudoEmail(v){const p=phone(v);return p?`p${p.replace(/\D/g,'')}@orzumall.phone`:''}
function safeId(v){return txt(v,160).replace(/[^a-zA-Z0-9_-]/g,'')}
function time(v){try{return v?.toMillis?v.toMillis():(v?.seconds?Number(v.seconds)*1000:(v?._seconds?Number(v._seconds)*1000:(+new Date(v)||0)))}catch(_){return 0}}
function publicName(u={},a={}){const clean=x=>{const s=txt(x,90);return !s||s.includes('@')?'':s};return[clean(u.firstName),clean(u.lastName)].filter(Boolean).join(' ')||clean(u.name)||clean(a.displayName)||'Foydalanuvchi'}
function makePassword(){return `Om${crypto.randomBytes(5).toString('base64url')}9!`}
function uidToNumericId(uid){const hex=String(uid||'').replace(/[^0-9a-f]/gi,'').padEnd(10,'0').slice(0,10);let n=0;try{n=parseInt(hex,16)}catch(_){n=Date.now()}return(n%900000)+100000}
async function actor(event){initAdmin();const token=bearer(event);if(!token)return{ok:false,status:401,error:'admin_login_required'};let d;try{d=await admin.auth().verifyIdToken(token)}catch(_){return{ok:false,status:401,error:'bad_token'}}const db=admin.firestore(),em=email(d.email);const configured=String(process.env.ADMIN_EMAILS||process.env.ORZUMALL_ADMIN_EMAILS||'').split(/[\s,;]+/).map(email).filter(Boolean);let allowed=new Set(['sohibjonmath@gmail.com',...configured]);try{const s=await db.doc('configs/admins').get();if(s.exists&&Array.isArray(s.data()?.emails))s.data().emails.map(email).filter(Boolean).forEach(x=>allowed.add(x))}catch(_){}if(!allowed.has(em))return{ok:false,status:403,error:'admin_required'};return{ok:true,uid:d.uid,email:em,db}}
async function audit(db,a,targetUid,action,meta={}){await db.collection('admin_user_audit').add({targetUid,action,actorUid:a.uid,actorEmail:a.email,meta,createdAt:admin.firestore.FieldValue.serverTimestamp()})}
async function listAllAuth(max=3000){let token,rows=[];do{const r=await admin.auth().listUsers(Math.min(1000,max-rows.length),token);rows.push(...r.users);token=r.pageToken}while(token&&rows.length<max);return rows}
function authPublic(a){if(!a)return{};return{uid:a.uid,email:a.email||'',displayName:a.displayName||'',disabled:!!a.disabled,emailVerified:!!a.emailVerified,createdAt:a.metadata?.creationTime||'',lastSignInAt:a.metadata?.lastSignInTime||'',providers:(a.providerData||[]).map(x=>x.providerId)}}
function profilePublic(uid,u={},a=null,agg={},topup=0){const authRow=authPublic(a),onlineUntilMs=num(u.onlineUntilMs,0),balanceUZS=Math.round(num(u.balanceUZS??u.balance,0));return{uid,numericId:u.numericId??'',name:publicName(u,authRow),firstName:txt(u.firstName,90),lastName:txt(u.lastName,90),phone:txt(u.phone||u.phoneNumber||u.tel,40),email:authRow.email||txt(u.email,180),displayName:authRow.displayName||'',balanceUZS,disabled:!!authRow.disabled,online:onlineUntilMs>Date.now(),onlineUntilMs,lastSeenAtMs:time(u.lastSeenAt||u.lastVisitAt),lastVisitAtMs:time(u.lastVisitAt||u.lastSeenAt),lastVisitPath:txt(u.lastVisitPath,240),lastDevice:txt(u.lastDevice,40),createdAtMs:time(u.createdAt)||(+new Date(authRow.createdAt)||0),lastSignInAtMs:+new Date(authRow.lastSignInAt)||0,profileCompleted:u.profileCompleted===true,telegramChatId:txt(u.telegramChatId||u.tgChatId,100),adminNote:txt(u.adminNote,600),adminExtra:u.adminExtra&&typeof u.adminExtra==='object'&&!Array.isArray(u.adminExtra)?u.adminExtra:{},ordersCount:num(agg.ordersCount,0),paidOrdersCount:num(agg.paidOrdersCount,0),spentUZS:Math.round(num(agg.spentUZS,0)),lastOrderAtMs:num(agg.lastOrderAtMs,0),approvedTopupUZS:Math.round(num(topup,0))}}
async function listUsers(db){const[authRows,userSnap,orderSnap,topupSnap]=await Promise.all([listAllAuth(3000),db.collection('users').limit(3000).get(),db.collection('orders').limit(6000).get(),db.collection('topup_requests').limit(6000).get().catch(()=>({docs:[]}))]);const amap=new Map(authRows.map(x=>[x.uid,x])),umap=new Map(userSnap.docs.map(d=>[d.id,d.data()||{}])),agg=new Map(),topups=new Map();for(const d of orderSnap.docs){const o=d.data()||{},uid=String(o.uid||'').trim();if(!uid)continue;const r=agg.get(uid)||{ordersCount:0,paidOrdersCount:0,spentUZS:0,lastOrderAtMs:0};r.ordersCount++;const paid=String(o.paymentStatus||'').toLowerCase()==='paid'||String(o.status||'').toLowerCase()==='delivered';if(paid){r.paidOrdersCount++;r.spentUZS+=num(o.totalUZS,0)}r.lastOrderAtMs=Math.max(r.lastOrderAtMs,time(o.createdAt));agg.set(uid,r)}for(const d of topupSnap.docs||[]){const r=d.data()||{},uid=String(r.uid||'').trim();if(uid&&String(r.status||'').toLowerCase()==='approved')topups.set(uid,num(topups.get(uid),0)+num(r.finalAmountUZS||r.amountUZS||r.amount,0))}const ids=[...new Set([...amap.keys(),...umap.keys()])];const users=ids.map(uid=>profilePublic(uid,umap.get(uid)||{},amap.get(uid)||null,agg.get(uid)||{},topups.get(uid)||0)).sort((a,b)=>(b.online-a.online)||(b.lastVisitAtMs-a.lastVisitAtMs)||(b.createdAtMs-a.createdAtMs));const now=Date.now();return{users,stats:{total:users.length,online:users.filter(x=>x.online).length,active24h:users.filter(x=>x.lastVisitAtMs>now-86400000).length,active7d:users.filter(x=>x.lastVisitAtMs>now-7*86400000).length,totalBalanceUZS:users.reduce((s,x)=>s+x.balanceUZS,0),totalSpentUZS:users.reduce((s,x)=>s+x.spentUZS,0),disabled:users.filter(x=>x.disabled).length}}}
function editableExtra(v){if(!v||typeof v!=='object'||Array.isArray(v))return{};const blocked=/^(?:uid|role|admin|permissions?|password|balance|balanceUZS|createdAt|updatedAt|lastSeenAt|lastVisitAt|onlineUntilMs|presenceUpdatedAt)$/i,out={};for(const[k,val]of Object.entries(v).slice(0,30)){const key=txt(k,60);if(!key||blocked.test(key))continue;if(['string','number','boolean'].includes(typeof val)||val===null)out[key]=typeof val==='string'?txt(val,400):val}return out}
exports.handler=async event=>{try{if(event.httpMethod==='OPTIONS')return json(204,{});if(event.httpMethod!=='POST')return json(405,{ok:false,error:'method_not_allowed'});const a=await actor(event);if(!a.ok)return json(a.status,{ok:false,error:a.error});let b={};try{b=JSON.parse(event.body||'{}')}catch(_){return json(400,{ok:false,error:'invalid_json'})}const action=txt(b.action,40).toLowerCase(),db=a.db;
  if(action==='list'){const out=await listUsers(db);return json(200,{ok:true,...out,onlineWindowSec:125})}
  if(action==='get'){const uid=safeId(b.uid);if(!uid)return json(400,{ok:false,error:'uid_required'});const[us,ar,logs]=await Promise.all([db.doc(`users/${uid}`).get(),admin.auth().getUser(uid).catch(()=>null),db.collection('admin_user_audit').where('targetUid','==',uid).limit(25).get().catch(()=>({docs:[]}))]);return json(200,{ok:true,user:profilePublic(uid,us.exists?(us.data()||{}):{},ar),audit:(logs.docs||[]).map(d=>({id:d.id,...d.data(),createdAtMs:time(d.data()?.createdAt)})).sort((x,y)=>y.createdAtMs-x.createdAtMs)})}
  if(action==='create'){const p=phone(b.phone),firstName=txt(b.firstName,90),lastName=txt(b.lastName,90),name=txt(b.name||`${firstName} ${lastName}`,160)||'Foydalanuvchi',password=txt(b.password,120)||makePassword();if(!p)return json(400,{ok:false,error:'valid_phone_required'});if(password.length<6)return json(400,{ok:false,error:'password_min_6'});const em=pseudoEmail(p);let rec;try{rec=await admin.auth().createUser({email:em,password,displayName:name,disabled:false})}catch(e){return json(409,{ok:false,error:String(e?.code||e?.message||e)})}const now=admin.firestore.FieldValue.serverTimestamp(),numericId=uidToNumericId(rec.uid);await db.doc(`users/${rec.uid}`).set({numericId,phone:p,email:em,firstName,lastName,name,balanceUZS:Math.max(0,Math.round(num(b.balanceUZS,0))),balance:Math.max(0,Math.round(num(b.balanceUZS,0))),profileCompleted:!!(firstName&&lastName&&p),createdAt:now,updatedAt:now,createdByAdmin:a.email,adminNote:txt(b.adminNote,600),adminExtra:editableExtra(b.adminExtra)},{merge:true});await db.doc(`users_by_numeric/${numericId}`).set({uid:rec.uid,updatedAt:now},{merge:true});await audit(db,a,rec.uid,'user_created',{phone:p,name,numericId});return json(200,{ok:true,uid:rec.uid,numericId,tempPassword:password})}
  const uid=safeId(b.uid);if(!uid)return json(400,{ok:false,error:'uid_required'});
  if(action==='save'){const ref=db.doc(`users/${uid}`),beforeSnap=await ref.get(),before=beforeSnap.exists?(beforeSnap.data()||{}):{},ar=await admin.auth().getUser(uid).catch(()=>null),p=b.phone!==undefined?phone(b.phone):txt(before.phone,40),firstName=txt(b.firstName??before.firstName,90),lastName=txt(b.lastName??before.lastName,90),name=txt(b.name||`${firstName} ${lastName}`||before.name,160)||'Foydalanuvchi',disabled=b.disabled===true;let balanceUZS=Math.max(0,Math.round(num(before.balanceUZS??before.balance,0)));if(b.balanceSet!==undefined&&b.balanceSet!=='')balanceUZS=Math.max(0,Math.round(num(b.balanceSet,balanceUZS)));if(b.balanceDelta!==undefined&&b.balanceDelta!=='')balanceUZS=Math.max(0,balanceUZS+Math.round(num(b.balanceDelta,0)));const patch={phone:p,firstName,lastName,name,balanceUZS,balance:balanceUZS,profileCompleted:!!(firstName&&lastName&&p),telegramChatId:txt(b.telegramChatId??before.telegramChatId,100),adminNote:txt(b.adminNote??before.adminNote,600),adminExtra:editableExtra(b.adminExtra),updatedAt:admin.firestore.FieldValue.serverTimestamp(),updatedByAdmin:a.email};await ref.set(patch,{merge:true});if(ar){const authPatch={displayName:name,disabled};if(p&&(!ar.email||/@orzumall\.phone$/i.test(ar.email)))authPatch.email=pseudoEmail(p);await admin.auth().updateUser(uid,authPatch);if(authPatch.email)await ref.set({email:authPatch.email},{merge:true})}await audit(db,a,uid,'user_updated',{name,phone:p,balanceBefore:Math.round(num(before.balanceUZS??before.balance,0)),balanceAfter:balanceUZS,disabled,note:txt(b.changeNote,300)});return json(200,{ok:true,balanceUZS})}
  if(action==='set_password'){let password=txt(b.password,120);if(!password)password=makePassword();if(password.length<6)return json(400,{ok:false,error:'password_min_6'});await admin.auth().updateUser(uid,{password});await admin.auth().revokeRefreshTokens(uid);await audit(db,a,uid,'password_reset',{temporary:true});return json(200,{ok:true,tempPassword:password})}
  if(action==='toggle_disabled'){const disabled=b.disabled===true;await admin.auth().updateUser(uid,{disabled});await audit(db,a,uid,disabled?'user_blocked':'user_unblocked',{});return json(200,{ok:true,disabled})}
  return json(400,{ok:false,error:'unknown_action'});
}catch(e){console.error('admin-users',e);return json(500,{ok:false,error:'server_error',detail:String(e?.message||e).slice(0,220)})}}
