// OrzuMall marketplace cash checkout: server-priced catalog snapshot + seller split
const admin=require('firebase-admin');
const {pushNewOrder}=require('./_adminPush');
const {pushOrderUpdate}=require('./_customerPush');
const {normalizePickupShipping}=require('./_pickupPointsCommon');
const M=require('./_marketplaceOrderCommon');
const PM=require('./_productMetricsCommon');
function initAdmin(){if(admin.apps.length)return;const b64=process.env.FIREBASE_SERVICE_ACCOUNT_B64;if(!b64)throw new Error('Missing env FIREBASE_SERVICE_ACCOUNT_B64');admin.initializeApp({credential:admin.credential.cert(JSON.parse(Buffer.from(b64,'base64').toString('utf8')))})}
function json(statusCode,body){return{statusCode,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)}}
function bearer(e){const m=String(e.headers?.authorization||e.headers?.Authorization||'').match(/^Bearer\s+(.+)$/i);return m?m[1]:''}
function cleanName(v){const s=String(v==null?'':v).trim().replace(/\s+/g,' ');return!s||s.includes('@')?'':s}
function customerName(u={},d={}){return[cleanName(u.firstName),cleanName(u.lastName)].filter(Boolean).join(' ')||cleanName(u.name)||cleanName(u.fullName)||cleanName(d.name)||'Mijoz'}
function shortId(len=6){return String(Math.floor(Math.random()*(10**len-1))+1).padStart(len,'0')}
async function allocate(db){for(let len=6;;len++){for(let i=0;i<60;i++){const id=shortId(len);if(!(await db.doc(`orders/${id}`).get()).exists)return id}}}
function deliveryFee(shipping,body){return Math.max(0,Math.min(500000,M.parsePrice(shipping?.deliveryFeeUZS??body?.deliveryFeeUZS??0)))}
exports.handler=async(event)=>{try{initAdmin();if(event.httpMethod!=='POST')return json(405,{ok:false,error:'method_not_allowed'});const token=bearer(event);if(!token)return json(401,{ok:false,error:'unauthorized'});let decoded;try{decoded=await admin.auth().verifyIdToken(token)}catch(_){return json(401,{ok:false,error:'bad_token'})}let body={};try{body=JSON.parse(event.body||'{}')}catch(_){return json(400,{ok:false,error:'invalid_json'})}const db=admin.firestore();let catalog;try{catalog=await M.loadCatalogLines(db,body.items)}catch(e){return json(400,{ok:false,error:String(e.message||e)})}let shipping=body.shipping&&typeof body.shipping==='object'?body.shipping:null;if(String(shipping?.method||shipping?.service||'').toLowerCase()==='pickup_point')shipping=await normalizePickupShipping(db,shipping,catalog.totalWeightKg);const deliveryFeeUZS=deliveryFee(shipping,body),totalUZS=catalog.subtotalUZS+deliveryFeeUZS;if(!totalUZS)return json(400,{ok:false,error:'total_invalid'});
let u={};try{const snap=await db.doc(`users/${decoded.uid}`).get();u=snap.exists?(snap.data()||{}):{}}catch(_){}const orderId=await allocate(db),now=admin.firestore.FieldValue.serverTimestamp(),shippingFinal=shipping||{method:'pickup',methodLabel:'Do‘kondan olib ketish',addressText:'Do‘kondan olib ketish',deliveryFeeUZS:0};const orderDoc={id:orderId,orderId,uid:decoded.uid,email:decoded.email||null,numericId:u.numericId!=null?String(u.numericId):null,userName:customerName(u,decoded),userPhone:String(u.phone||u.phoneNumber||u.tel||''),userTgChatId:String(u.telegramChatId||u.tgChatId||'').trim()||null,firstName:String(u.firstName||'')||null,lastName:String(u.lastName||'')||null,status:'new',paymentStatus:'cash_on_delivery',statusActor:'system',statusUpdatedAt:now,statusHistory:[{status:'new',action:'created',actorType:'system',actorName:'OrzuMall',reason:'Buyurtma qabul qilindi',at:admin.firestore.Timestamp.now()}],items:catalog.lines,totalUZS,productsTotalUZS:catalog.subtotalUZS,deliveryFeeUZS,amountTiyin:null,provider:'cash',currency:'UZS',pricing:{subtotalUZS:catalog.subtotalUZS,deliveryFeeUZS,discountUZS:0,totalUZS},shipping:shippingFinal,orderType:'checkout',note:M.cleanText(body.note,500),source:'web',createdAt:now,...catalog.sellerSummary};await db.doc(`orders/${orderId}`).set(orderDoc,{merge:false});await PM.recordPurchaseMetrics(db,catalog.lines,orderId).catch(()=>{});await pushNewOrder(db,orderDoc).catch(()=>{});await pushOrderUpdate(db,decoded.uid,orderId,'Buyurtmangiz qabul qilindi',`#${orderId} buyurtma qabul qilindi. Holati: Yangi.`).catch(()=>{});return json(200,{ok:true,orderId,totalUZS})}catch(e){console.error('createOrderCash',e);return json(500,{ok:false,error:'server_error',detail:String(e?.message||e).slice(0,180)})}};
