const C=require('./_sellerCommon');
const F=()=>C.admin.firestore.FieldValue;
const T=()=>C.admin.firestore.Timestamp;
function text(v,n=120){return C.safeText(v,n)}
function num(v,min=0,max=1e12){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):min}
function code(v){return text(v,40).toUpperCase().replace(/[^A-Z0-9_-]+/g,'')}
function timeMs(v){try{return v?.toMillis?v.toMillis():Number(v?.seconds||v?._seconds||0)*1000||Number(v)||0}catch(_){return 0}}
function parseTime(v){const s=text(v,80);if(!s)return null;const ms=Date.parse(s);return Number.isFinite(ms)&&ms>0?T().fromMillis(ms):null}
function publicPromo(id,d={}){return{id:String(id||''),code:String(id||''),active:d.active!==false,type:String(d.type||'percent'),value:Number(d.value||0),minOrderUZS:num(d.minOrderUZS),maxDiscountUZS:num(d.maxDiscountUZS),usageLimit:num(d.usageLimit),usedCount:num(d.usedCount),perUserLimit:num(d.perUserLimit??1,0,100000),startAtMs:timeMs(d.startAt),expiresAtMs:timeMs(d.expiresAt),createdAtMs:timeMs(d.createdAt),updatedAtMs:timeMs(d.updatedAt)}}
exports.handler=async event=>{try{C.initAdmin();if(event.httpMethod!=='POST')return C.json(405,{ok:false,error:'method_not_allowed'});const decoded=await C.verifyToken(event);const db=C.admin.firestore();if(!await C.isAdmin(decoded,db))return C.json(403,{ok:false,error:'admin_required'});let body={};try{body=JSON.parse(event.body||'{}')}catch(_){return C.json(400,{ok:false,error:'invalid_json'})}const action=text(body.action,40);
 if(action==='list'){const snap=await db.collection('promocodes').limit(400).get();const promos=snap.docs.map(d=>publicPromo(d.id,d.data()||{})).sort((a,b)=>(b.updatedAtMs||b.createdAtMs)-(a.updatedAtMs||a.createdAtMs));return C.json(200,{ok:true,promos})}
 if(action==='save'){const c=code(body.code);if(c.length<3)return C.json(400,{ok:false,error:'code_min_3'});const type=String(body.type||'percent').toLowerCase()==='fixed'?'fixed':'percent',value=type==='percent'?num(body.value,1,100):num(body.value,1,100000000),ref=db.doc(`promocodes/${c}`),snap=await ref.get(),old=snap.exists?(snap.data()||{}):{},patch={active:body.active!==false,type,value,minOrderUZS:num(body.minOrderUZS,0,1000000000),maxDiscountUZS:num(body.maxDiscountUZS,0,1000000000),usageLimit:num(body.usageLimit,0,10000000),perUserLimit:num(body.perUserLimit??1,0,10000),startAt:parseTime(body.startAt),expiresAt:parseTime(body.expiresAt),usedCount:num(old.usedCount||0),updatedAt:F().serverTimestamp(),updatedBy:String(decoded.email||decoded.uid||'admin')};if(!snap.exists)patch.createdAt=F().serverTimestamp();await ref.set(patch,{merge:true});const out=await ref.get();return C.json(200,{ok:true,promo:publicPromo(c,out.data()||{})})}
 if(action==='toggle'){const c=code(body.code);if(!c)return C.json(400,{ok:false,error:'code_required'});await db.doc(`promocodes/${c}`).set({active:body.active!==false,updatedAt:F().serverTimestamp(),updatedBy:String(decoded.email||decoded.uid||'admin')},{merge:true});return C.json(200,{ok:true})}
 if(action==='delete'){const c=code(body.code);if(!c)return C.json(400,{ok:false,error:'code_required'});const ref=db.doc(`promocodes/${c}`),snap=await ref.get();if(!snap.exists)return C.json(404,{ok:false,error:'not_found'});const d=snap.data()||{};if(num(d.usedCount)>0){await ref.set({active:false,archived:true,updatedAt:F().serverTimestamp(),updatedBy:String(decoded.email||decoded.uid||'admin')},{merge:true});return C.json(200,{ok:true,archived:true})}await ref.delete();return C.json(200,{ok:true,deleted:true})}
 return C.json(400,{ok:false,error:'unknown_action'});
}catch(e){const m=String(e?.message||e).slice(0,180);console.error('promo-admin',e);return C.json(m==='unauthorized'?401:500,{ok:false,error:m||'server_error'})}};
