const C=require('./_sellerCommon');
const F=()=>C.admin.firestore.FieldValue;
const DEFAULT_CATEGORIES=[
{id:'beauty',name:'Go‘zallik va parvarish',children:[{id:'skincare',name:'Yuz parvarishi'},{id:'haircare',name:'Soch parvarishi'},{id:'bodycare',name:'Tana parvarishi'},{id:'depilation',name:'Depilyatsiya'},{id:'perfume',name:'Atirlar'},{id:'beauty-tools',name:'Kosmetik aksessuarlar'}]},
{id:'electronics',name:'Elektronika',children:[{id:'phones',name:'Telefonlar'},{id:'phone-accessories',name:'Telefon aksessuarlari'},{id:'audio',name:'Audio'},{id:'smart-devices',name:'Smart qurilmalar'}]},
{id:'home',name:'Uy-ro‘zg‘or',children:[{id:'kitchen',name:'Oshxona'},{id:'cleaning',name:'Tozalash'},{id:'storage',name:'Saqlash va tartib'},{id:'home-decor',name:'Dekor'}]},
{id:'fashion',name:'Kiyim va aksessuarlar',children:[{id:'women-fashion',name:'Ayollar uchun'},{id:'men-fashion',name:'Erkaklar uchun'},{id:'bags',name:'Sumka va hamyonlar'},{id:'jewelry',name:'Bijuteriya'}]},
{id:'health',name:'Sog‘liq va gigiyena',children:[{id:'hygiene',name:'Gigiyena'},{id:'wellness',name:'Wellness'}]},
{id:'kids',name:'Bolalar tovarlari',children:[{id:'kids-care',name:'Bolalar parvarishi'},{id:'toys',name:'O‘yinchoqlar'}]},
{id:'other',name:'Boshqa mahsulotlar',children:[{id:'other-products',name:'Turli mahsulotlar'}]}
];
const arr=v=>Array.isArray(v)?v:[];
const cleanImages=v=>arr(v).map(x=>C.safeText(x,900)).filter(Boolean).slice(0,16);
const cleanTextArray=(v,max=60,limit=40)=>arr(v).map(x=>C.safeText(x,max)).filter(Boolean).slice(0,limit);
const cleanSku=v=>C.safeText(v,100).toUpperCase().replace(/[^A-Z0-9А-ЯЁЎҒҚҲ_-]+/gi,'').slice(0,100);
const money=v=>Math.max(0,Math.round(Number(v)||0));
const ts=v=>{try{return Number(v?.seconds??v?._seconds??0)*1000||Number(new Date(v))||0}catch(_){return 0}};
function cleanColors(v){return arr(v).map(x=>({name:C.safeText(typeof x==='string'?x:x?.name,80),hex:C.safeText(x?.hex||'#D4AF37',20)})).filter(x=>x.name).slice(0,30)}
function cleanVariants(v){return arr(v).map(x=>({color:C.safeText(x?.color,80)||null,size:C.safeText(x?.size,80)||null,price:money(x?.price??x?.priceUZS),oldPrice:money(x?.oldPrice),sku:cleanSku(x?.sku),stockQty:Math.max(0,Math.round(Number(x?.stockQty)||0))})).filter(x=>x.price>0).slice(0,100)}
function cleanImagesByColor(v){const out={};if(v&&typeof v==='object')Object.entries(v).slice(0,30).forEach(([k,urls])=>{const key=C.safeText(k,80),list=cleanImages(urls);if(key&&list.length)out[key]=list});return out}
function statusNorm(v){const s=C.safeText(v||'new',40).toLowerCase();return({pending:'new',processing:'packing',shipped:'shipping',completed:'delivered',canceled:'cancelled'}[s]||s)}
function finalSellerStatus(order,sellerId){const global=statusNorm(order.status),local=statusNorm(order?.sellerProgress?.[sellerId]?.status||'new');return['cancelled','returned','return_rejected','delivered'].includes(global)?global:local}
function productPublic(d){return{id:String(d.id||''),name:String(d.name||''),name_ru:String(d.name_ru||''),description:String(d.description||''),description_ru:String(d.description_ru||''),price:Number(d.price||0)||0,oldPrice:Number(d.oldPrice||0)||0,popularScore:C.num(d.popularScore,0,100),status:String(d.status||'pending'),moderationReason:String(d.moderationReason||''),moderationNote:String(d.moderationNote||d.rejectedReason||''),sellerSubmissionNote:String(d.sellerSubmissionNote||''),images:cleanImages(d.images),imagesByColor:cleanImagesByColor(d.imagesByColor),categoryId:String(d.categoryId||''),subcategoryId:String(d.subcategoryId||''),categoryPathIds:cleanTextArray(d.categoryPathIds,80,6),sku:String(d.sku||''),stockQty:Number(d.stockQty||0)||0,weightKg:Number(d.weightKg||0)||0,productType:String(d.productType||''),youtubeUrl:String(d.youtubeUrl||d.videoUrl||''),tags:cleanTextArray(d.tags,80,40),colors:cleanColors(d.colors),sizes:cleanTextArray(d.sizes,80,30),variants:cleanVariants(d.variants),fulfillmentType:String(d.fulfillmentType||'stock'),deliveryMinDays:Number(d.deliveryMinDays||1)||1,deliveryMaxDays:Number(d.deliveryMaxDays||7)||7,prepayRequired:!!d.prepayRequired,createdAt:d.createdAt||null,updatedAt:d.updatedAt||null}}
async function categories(db){try{const s=await db.doc('configs/categories').get();const d=s.exists?s.data()||{}:{};return arr(d.tree).length?d.tree:(arr(d.categories).length?d.categories:DEFAULT_CATEGORIES)}catch(_){return DEFAULT_CATEGORIES}}
function sellerItems(order,sellerId){return arr(order.items).filter(it=>C.safeId(it?.sellerId||'orzumall')===sellerId)}
function lineGross(it){return money(it?.sellerGrossUZS??it?.lineTotalUZS??((Number(it?.unitPriceUZS||it?.priceUZS||it?.price)||0)*(Number(it?.qty||1)||1)))}
function orderAccounting(order,sellerId,items){const a=order?.sellerAccounting?.[sellerId]||{};const gross=money(a.grossUZS||items.reduce((s,x)=>s+lineGross(x),0)),commission=money(a.commissionUZS),net=money(a.netUZS||(gross-commission));return{grossUZS:gross,commissionUZS:commission,netUZS:net,commissionPercent:Number(a.commissionPercent||0),itemCount:items.reduce((s,x)=>s+(Number(x.qty)||1),0)}}
function projectOrder(order,sellerId){const items=sellerItems(order,sellerId);if(!items.length)return null;const a=orderAccounting(order,sellerId,items),sellerStatus=finalSellerStatus(order,sellerId);return{id:String(order.id||order.orderId||''),orderId:String(order.orderId||order.id||''),userName:String(order.userName||'Mijoz'),userPhone:String(order.userPhone||''),shipping:order.shipping||null,provider:String(order.provider||''),paymentStatus:String(order.paymentStatus||''),createdAt:order.createdAt||null,updatedAt:order.updatedAt||null,orderStatus:statusNorm(order.status),status:sellerStatus,sellerStatus,sellerProgress:order?.sellerProgress?.[sellerId]||null,statusNote:String(order.statusNote||''),items,totalUZS:a.grossUZS,productsTotalUZS:a.grossUZS,originalTotalUZS:money(order.totalUZS),sellerGrossUZS:a.grossUZS,sellerCommissionUZS:a.commissionUZS,sellerNetUZS:a.netUZS,sellerCommissionPercent:a.commissionPercent,itemCount:a.itemCount,shippingFeeUZS:money(order.deliveryFeeUZS),returnRequest:order.returnRequest||null,cancellation:order.cancellation||null}}
async function rawOrders(db,sellerId){let docs=[];try{const s=await db.collection('orders').where('sellerIds','array-contains',sellerId).limit(400).get();docs=s.docs}catch(_){try{const s=await db.collection('orders').orderBy('createdAt','desc').limit(600).get();docs=s.docs}catch(__){const s=await db.collection('orders').limit(600).get();docs=s.docs}}return docs.map(d=>({id:d.id,...d.data()})).filter(o=>sellerItems(o,sellerId).length)}
async function payouts(db,sellerId){try{const s=await db.collection('sellerPayouts').where('sellerId','==',sellerId).limit(300).get();return s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>ts(b.createdAt||b.paidAt)-ts(a.createdAt||a.paidAt))}catch(_){return[]}}
async function orderDashboard(db,sellerId){const raw=await rawOrders(db,sellerId),orders=raw.map(o=>projectOrder(o,sellerId)).filter(Boolean).sort((a,b)=>ts(b.createdAt)-ts(a.createdAt)),pay=await payouts(db,sellerId);const stats={total:orders.length,new:0,packing:0,ready:0,handed_over:0,shipping:0,delivered:0,cancelled:0,returned:0,totalItems:0,deliveredItems:0,deliveredGrossUZS:0,deliveredNetUZS:0,pendingNetUZS:0};orders.forEach(o=>{stats[o.sellerStatus]=(stats[o.sellerStatus]||0)+1;stats.totalItems+=o.itemCount;if(o.sellerStatus==='delivered'){stats.deliveredItems+=o.itemCount;stats.deliveredGrossUZS+=o.sellerGrossUZS;stats.deliveredNetUZS+=o.sellerNetUZS}else if(!['cancelled','returned','return_rejected'].includes(o.sellerStatus))stats.pendingNetUZS+=o.sellerNetUZS});const paidUZS=pay.filter(x=>String(x.status||'paid').toLowerCase()==='paid').reduce((s,x)=>s+money(x.amountUZS||x.amount),0);const accounting={availableBalanceUZS:Math.max(0,stats.deliveredNetUZS-paidUZS),pendingBalanceUZS:stats.pendingNetUZS,totalSalesUZS:stats.deliveredGrossUZS,totalNetUZS:stats.deliveredNetUZS,paidOutUZS:paidUZS,commissionUZS:Math.max(0,stats.deliveredGrossUZS-stats.deliveredNetUZS)};const paymentHistory=[...pay.map(x=>({id:x.id,type:'payout',status:String(x.status||'paid'),amountUZS:money(x.amountUZS||x.amount),createdAt:x.paidAt||x.createdAt||null,note:String(x.note||'Sellerga to‘lov')})),...orders.filter(x=>x.sellerStatus==='delivered').map(x=>({id:x.orderId,type:'sale',status:'available',amountUZS:x.sellerNetUZS,createdAt:x.updatedAt||x.createdAt,note:`#${x.orderId} sotuv hisoblandi`}))].sort((a,b)=>ts(b.createdAt)-ts(a.createdAt)).slice(0,300);return{orders,orderStats:stats,accounting,payouts:pay,paymentHistory}}
function fingerprint(x){return JSON.stringify(x)}
exports.handler=async(event)=>{try{C.initAdmin();if(event.httpMethod!=='POST')return C.json(405,{ok:false,error:'method_not_allowed'});let decoded;try{decoded=await C.verifyToken(event)}catch(_){return C.json(401,{ok:false,error:'bad_token'})}const db=C.admin.firestore();let seller;try{seller=await C.getSellerByDecoded(db,decoded)}catch(e){return C.json(403,{ok:false,error:String(e.message||e)})}let body={};try{body=JSON.parse(event.body||'{}')}catch(_){return C.json(400,{ok:false,error:'invalid_json'})}const action=C.safeText(body.action,80)||'dashboard';
if(action==='dashboard'){const stats=await C.sellerStats(db,seller.id),od=await orderDashboard(db,seller.id);return C.json(200,{ok:true,seller:C.publicSeller(seller),stats:{productCount:stats.productCount,avgProductPopularity:stats.avgProductPopularity,pendingCount:stats.pendingCount,approvedCount:stats.approvedCount},products:stats.products.map(productPublic),categories:await categories(db),...od})}
if(action==='product_save'){const input=body.product||{},id=C.safeId(input.id||'')||`${seller.id}-${Date.now().toString(36)}`,ref=db.doc(`products/${id}`),snap=await ref.get(),old=snap.exists?snap.data()||{}:{};if(snap.exists&&String(old.sellerId||'')!==seller.id)return C.json(403,{ok:false,error:'product_owner_required'});const name=C.safeText(input.name,180),price=money(input.price);if(!name||!price)return C.json(400,{ok:false,error:'name_price_required'});const fulfillmentType=['stock','cargo'].includes(String(input.fulfillmentType))?String(input.fulfillmentType):'stock',min=Math.max(1,Math.round(Number(input.deliveryMinDays)||(fulfillmentType==='cargo'?15:1))),max=Math.max(min,Math.round(Number(input.deliveryMaxDays)||(fulfillmentType==='cargo'?30:7)));const categoryPathIds=cleanTextArray(input.categoryPathIds,80,6),categoryId=C.safeText(input.categoryId||categoryPathIds[0],80),subcategoryId=C.safeText(input.subcategoryId||categoryPathIds[1],80);const core={name,name_ru:C.safeText(input.name_ru,180),description:C.safeText(input.description,5000),description_ru:C.safeText(input.description_ru,5000),price,oldPrice:money(input.oldPrice),weightKg:Math.max(0,Number(input.weightKg)||0),sku:cleanSku(input.sku)||`${seller.id}-${id}`.toUpperCase().slice(0,100),stockQty:Math.max(0,Math.round(Number(input.stockQty)||0)),productType:['original','oem','replica'].includes(String(input.productType))?String(input.productType):'',youtubeUrl:C.safeText(input.youtubeUrl||input.videoUrl,900),categoryId,subcategoryId,categoryPathIds,tags:cleanTextArray(input.tags,80,40),colors:cleanColors(input.colors),sizes:cleanTextArray(input.sizes,80,30),variants:cleanVariants(input.variants),images:cleanImages(input.images),imagesByColor:cleanImagesByColor(input.imagesByColor),fulfillmentType,deliveryMinDays:min,deliveryMaxDays:max,prepayRequired:fulfillmentType==='cargo',sellerSubmissionNote:C.safeText(input.sellerSubmissionNote,1000)};const changed=!snap.exists||fingerprint(core)!==fingerprint(Object.fromEntries(Object.keys(core).map(k=>[k,old[k]??(Array.isArray(core[k])?[]:(typeof core[k]==='object'?{}:''))])));const data={...core,popularScore:C.num(old.popularScore,0,100),sellerId:seller.id,sellerName:seller.storeName,sellerLogo:seller.logoUrl,sellerBanner:seller.bannerUrl||'',sellerDescription:seller.description||'',sellerWorkingHours:seller.workingHours||'',sellerPhone:seller.phone,sellerPopularity:C.num(seller.popularity,0,100),sellerVerified:seller.verified!==false,sellerActive:true,ownerUid:C.sellerUid(seller.id),ownerType:'seller',createdByRole:'seller',isOrzuMallVerified:false,currency:'UZS',status:changed?'pending':String(old.status||'pending'),moderationReason:changed?(snap.exists?'seller_updated_product':'seller_new_product'):String(old.moderationReason||''),createdAt:old.createdAt||F().serverTimestamp(),updatedAt:F().serverTimestamp()};await ref.set(data,{merge:true});return C.json(200,{ok:true,id,status:data.status})}
if(action==='product_delete'){const id=C.safeId(body.id),ref=db.doc(`products/${id}`),snap=await ref.get();if(!snap.exists)return C.json(404,{ok:false,error:'product_not_found'});if(String(snap.data()?.sellerId||'')!==seller.id)return C.json(403,{ok:false,error:'product_owner_required'});await ref.set({status:'deleted',deletedAt:F().serverTimestamp(),updatedAt:F().serverTimestamp()},{merge:true});return C.json(200,{ok:true})}
if(action==='order_action'){const orderId=C.safeId(body.orderId),next=C.safeText(body.status,40).toLowerCase();if(!orderId||!['packing','ready','handed_over'].includes(next))return C.json(400,{ok:false,error:'invalid_order_action'});const ref=db.doc(`orders/${orderId}`);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error('order_not_found');const order={id:snap.id,...snap.data()},items=sellerItems(order,seller.id);if(!items.length)throw new Error('order_owner_required');const global=statusNorm(order.status);if(['cancelled','returned','delivered'].includes(global))throw new Error('order_final');const current=statusNorm(order?.sellerProgress?.[seller.id]?.status||'new');const allowed={packing:['new','paid'],ready:['new','paid','packing'],handed_over:['ready']}[next];if(!allowed.includes(current))throw new Error('order_transition_not_allowed');const itemCount=items.reduce((s,x)=>s+(Number(x.qty)||1),0),subtotalUZS=items.reduce((s,x)=>s+lineGross(x),0),progress={sellerId:seller.id,sellerName:seller.storeName,status:next,itemCount,subtotalUZS,updatedAt:C.admin.firestore.Timestamp.now()};const all={...(order.sellerProgress||{}),[seller.id]:progress},patch={[`sellerProgress.${seller.id}`]:progress,sellerProgressHistory:F().arrayUnion({sellerId:seller.id,sellerName:seller.storeName,status:next,at:C.admin.firestore.Timestamp.now()}),updatedAt:F().serverTimestamp()};if(global==='new'&&next==='packing'){patch.status='packing';patch.statusUpdatedAt=F().serverTimestamp()}if(Object.values(all).length&&Object.values(all).every(x=>statusNorm(x.status)==='handed_over')){patch.status='shipping';patch.statusUpdatedAt=F().serverTimestamp()}tx.update(ref,patch)});return C.json(200,{ok:true,status:next})}
return C.json(400,{ok:false,error:'unknown_action'})}catch(e){console.error('seller-portal',e);const m=String(e?.message||e).slice(0,180)||'server_error';const code=m==='order_not_found'?404:(m==='order_owner_required'?403:(['order_final','order_transition_not_allowed'].includes(m)?409:500));return C.json(code,{ok:false,error:m})}};
