(() => {
  const VERSION='3.3.0';
  const BUTTON_ID='orzumall-market-import-btn';
  const MAX_IMAGES=18, MAX_GROUPS=8, MAX_OPTIONS=48;
  const txt=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
  const uniq=rows=>[...new Set((rows||[]).filter(Boolean))];
  const host=location.hostname.toLowerCase();
  const platform=host==='sahiy.uz'||host.endsWith('.sahiy.uz')?'sahiy':host==='uzum.uz'||host.endsWith('.uzum.uz')?'uzum':host==='yangkeduo.com'||host.endsWith('.yangkeduo.com')||host==='pinduoduo.com'||host.endsWith('.pinduoduo.com')?'pinduoduo':'';
  if(!platform)return;
  const specs={sahiy:{label:'Sahiy Market',currency:'UZS'},uzum:{label:'Uzum Market',currency:'UZS'},pinduoduo:{label:'Pinduoduo',currency:'CNY'}};
  const spec=specs[platform];
  const bad=/icon|logo|sprite|avatar|qrcode|qr-code|favicon|loading|placeholder|default|emoji|badge|cart|chat|video-play|review|comment|feedback|user|seller|brand/i;
  const isImage=u=>/\.(?:jpe?g|png|webp|avif)(?:[?#]|$)/i.test(u||'');
  function abs(v){let raw=txt(v).replace(/&amp;/g,'&').replace(/\\u002F/gi,'/').replace(/\\\//g,'/').replace(/^url\(["']?|["']?\)$/g,'');if(!raw||raw.startsWith('data:')||raw.startsWith('blob:'))return'';try{const u=new URL(raw.startsWith('//')?'https:'+raw:raw,location.href);if(!/^https?:$/i.test(u.protocol))return'';u.hash='';return u.toString()}catch{return''}}
  function attrUrls(node){const out=[];if(!node)return out;['currentSrc','src','data-src','data-lazy-src','data-original','data-origin-src','data-image','data-img','data-url','data-zoom-image','poster','data-bg'].forEach(k=>out.push(k==='currentSrc'?node.currentSrc:node.getAttribute?.(k)));const srcset=node.getAttribute?.('srcset')||'';srcset.split(',').forEach(x=>out.push(x.trim().split(/\s+/)[0]));const bg=node.style?.backgroundImage||'';String(bg).replace(/url\(["']?(.+?)["']?\)/g,(_m,u)=>{out.push(u);return _m});return uniq(out.map(abs).filter(u=>u&&isImage(u)&&!bad.test(u)))}
  function meta(name){return document.querySelector(`meta[property="${name}"],meta[name="${name}"],meta[itemprop="${name}"]`)?.content||''}
  function title(){return txt(document.querySelector('h1')?.textContent||meta('og:title')||meta('twitter:title')||document.title).slice(0,520)}
  function images(){const scored=[];const add=(url,score)=>{url=abs(url);if(url&&isImage(url)&&!bad.test(url))scored.push({url,score})};add(meta('og:image'),900);add(meta('twitter:image'),820);document.querySelectorAll('img,picture source,[style*="background-image"]').forEach(node=>{const r=node.getBoundingClientRect?.()||{};const w=Number(node.naturalWidth||r.width||0),h=Number(node.naturalHeight||r.height||0);const visible=(r.width||w)>=42&&(r.height||h)>=42;const top=Number(r.top||0);let score=Math.min(900,w*h/1000)+(top<950?180:0)+((r.left||0)<innerWidth*.75?100:0);if(!visible)score-=400;attrUrls(node).forEach(u=>add(u,score))});const map=new Map();scored.sort((a,b)=>b.score-a.score).forEach(row=>{if(!map.has(row.url))map.set(row.url,row)});return[...map.values()].slice(0,MAX_IMAGES).map(x=>x.url)}
  function parsePrice(){const candidates=[meta('product:price:amount'),meta('price'),...Array.from(document.querySelectorAll('[itemprop="price"],[data-price],[class*="price"],[class*="Price"]')).slice(0,60).map(x=>x.getAttribute('content')||x.getAttribute('data-price')||x.textContent)];for(const raw of candidates){const m=String(raw||'').replace(/[\s,]/g,'').match(/\d+(?:\.\d+)?/);if(!m)continue;const n=Number(m[0]);if(!Number.isFinite(n)||n<=0)continue;return spec.currency==='UZS'?{priceValue:n,priceUzs:Math.round(n),priceCurrency:'UZS'}:{priceValue:n,priceCny:n,priceCurrency:'CNY'}}return{priceValue:0,priceCurrency:spec.currency}}
  function moneyNumber(raw){const n=Number(String(raw||'').replace(/[^0-9]/g,''));return Number.isFinite(n)?n:0}
  function parseSahiyLogistics(){if(platform!=='sahiy')return{};const body=txt(document.body?.innerText||'');const domestic=(body.match(/Xitoy\s+ichida\s+yetkazish\s*([0-9\s.,]+)\s*so['‘’]?m/i)||[])[1]||'';const free=(body.match(/([0-9]+(?:[.,][0-9]+)?)\s*kg\s*gacha/i)||[])[1]||'';const extra=(body.match(/(?:qo['‘’]?shimcha|ortiqcha)\s*kg\s*uchun\s*([0-9\s.,]+)\s*so['‘’]?m/i)||body.match(/har\s+bir\s+qo['‘’]?shimcha\s+kg\s+uchun\s*([0-9\s.,]+)\s*so['‘’]?m/i)||[])[1]||'';return{chinaDomesticFeeUzs:moneyNumber(domestic),chinaFreeWeightKg:Number(String(free).replace(',','.'))||7,chinaExtraKgRateUzs:moneyNumber(extra)||77777}}
  function cleanLabel(v){return txt(v).replace(/^[\s:：/_-]+|[\s:：/_-]+$/g,'').slice(0,100)}
  function goodLabel(v){const s=cleanLabel(v);return!!s&&s.length<=80&&!/savat|savatcha|xarid|buyurtma|yetkaz|kafolat|tavsif|sharh|narx|price|delivery|review|comment|login|kirish|注册|登录|评价|详情|库存|¥|￥/i.test(s)}
  function optionImage(node){return attrUrls(node.matches?.('img')?node:(node.querySelector?.('img')||node))[0]||''}
  function scopeName(scope,index){const own=scope.getAttribute?.('data-name')||scope.getAttribute?.('aria-label')||scope.querySelector?.('h2,h3,h4,h5,strong,b,label')?.textContent||scope.previousElementSibling?.textContent||'';const clean=cleanLabel(own);return goodLabel(clean)&&clean.length<45?clean:`Variant ${index+1}`}
  function groups(){const scopes=[...document.querySelectorAll('[class*="sku"],[class*="Sku"],[class*="variant"],[class*="Variant"],[class*="option"],[class*="Option"],[data-sku],[data-testid*="variant"],[aria-label*="variant"],[class*="color"],[class*="size"]')].slice(0,220);const out=[];const seen=new Set();for(const scope of scopes){if(out.length>=MAX_GROUPS)break;const nodes=[...scope.querySelectorAll('button,label,li,[role="option"],[data-value],[class*="item"],[class*="Item"]')].slice(0,90);const opts=[];const names=new Set();for(const node of nodes){let name=cleanLabel(node.getAttribute?.('data-value')||node.getAttribute?.('aria-label')||node.textContent||node.querySelector?.('img')?.alt||'');if(!goodLabel(name)||names.has(name.toLowerCase()))continue;names.add(name.toLowerCase());opts.push({id:`o${opts.length+1}`,name,...(optionImage(node)?{image:optionImage(node)}:{})});if(opts.length>=MAX_OPTIONS)break}if(opts.length<2||opts.length>MAX_OPTIONS)continue;const name=scopeName(scope,out.length),key=name.toLowerCase()+'::'+opts.map(x=>x.name.toLowerCase()).join('|');if(seen.has(key))continue;seen.add(key);out.push({id:`g${out.length+1}`,name,type:/rang|color|colour|颜色/i.test(name)?'color':/size|razmer|o['‘’]?lcham|尺码|尺寸/i.test(name)?'size':'other',options:opts})}return out}
  function itemId(){const s=location.href;const patterns=platform==='pinduoduo'?[/goods_id=([0-9]{5,})/i,/(?:goods|product)[\/-]([0-9]{5,})/i]:platform==='uzum'?[/product[\/-][^/?#]*?-([0-9]{4,})(?:[/?#]|$)/i,/(?:product|products)[\/-]([0-9]{4,})/i,/(?:id|productId)=([0-9]{4,})/i]:[/(?:products?|goods?|item)[\/-]([0-9A-Za-z_-]{4,})/i,/(?:id|productId|itemId)=([0-9A-Za-z_-]{4,})/i];for(const re of patterns){const m=s.match(re);if(m)return m[1]}return location.pathname.split('/').filter(Boolean).pop()?.replace(/[^0-9A-Za-z_-]/g,'')||''}
  function combinations(optionGroups){if(!optionGroups.length)return[];let rows=[{selections:{}}];for(const group of optionGroups){rows=rows.flatMap(row=>group.options.slice(0,30).map(opt=>({selections:{...row.selections,[group.id]:opt.name}}))).slice(0,220)}return rows.map((row,i)=>({id:`generated-${i+1}`,skuId:`generated-${i+1}`,name:Object.values(row.selections).join(' / '),selections:row.selections,attributes:row.selections,stock:0}))}
  function extract(){const galleryImages=images(),variantGroups=groups(),skuVariants=combinations(variantGroups),logistics=parseSahiyLogistics();return{id:itemId(),url:location.href,sourcePlatform:platform,sourceLabel:spec.label,title:title(),images:galleryImages,galleryImages,variantGroups,skuVariants,priceCurrency:spec.currency,...parsePrice(),...logistics,moq:1,stock:0,diagnostics:{mode:'page-dom',galleryCount:galleryImages.length,groupCount:variantGroups.length,skuCount:skuVariants.length,chinaDomesticFeeUzs:logistics.chinaDomesticFeeUzs||0},extractedAt:new Date().toISOString(),extractorVersion:VERSION}}
  async function send(){const payload=extract();if(!payload.title&&!payload.images.length)throw new Error('Mahsulot ma’lumoti topilmadi. Mahsulot sahifasini to‘liq oching.');return chrome.runtime.sendMessage({type:'IMPORT_TO_ORZUMALL',payload})}
  function addButton(){if(document.getElementById(BUTTON_ID))return;const b=document.createElement('button');b.id=BUTTON_ID;b.type='button';b.textContent='OrzuMall’ga import';b.style.cssText='position:fixed;right:18px;bottom:86px;z-index:2147483647;border:0;border-radius:999px;background:#e91d35;color:#fff;padding:13px 17px;font:700 14px Arial;box-shadow:0 10px 30px rgba(15,23,42,.24);cursor:pointer';b.addEventListener('click',async()=>{const old=b.textContent;b.disabled=true;b.textContent='Yig‘ilmoqda...';try{await send();b.textContent='Admin ochildi'}catch(e){b.textContent=e.message||'Xato';setTimeout(()=>{b.textContent=old;b.disabled=false},2600)}});document.body.appendChild(b)}
  chrome.runtime.onMessage.addListener((message,_sender,reply)=>{if(message?.type!=='EXTRACT_AND_IMPORT')return false;send().then(()=>reply({ok:true})).catch(e=>reply({ok:false,error:e.message||'IMPORT_FAILED'}));return true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButton);else addButton();setTimeout(addButton,1800);
})();
